makanan = set([
    "Abangan", 
    "Abon Varia", 
    "Acar Kuning Ala Maluku", 
    "Adon-Adon Coro", 
    "Air Mata Pengantin", 
    "Air Tahu", 
    "Akar Pinang", 
    "Ale Ale", 
    "Ale-ale", 
    "Alen alen", 
    "Ambokueh", 
    "Amparan Tatak Pisang", 
    "Amparan Tatak Sagu", 
    "Ampyang", 
    "Ampyang Kacang", 
    "Angsle", 
    "Antor Tegal", 
    "Anuve Habre", 
    "Apam Barabai", 
    "Apam Baras", 
    "Apam Parangge", 
    "Apang", 
    "Apang Paranggi", 
    "Apang coe", 
    "Apang kenari", 
    "Apem Ceylon", 
    "Apem Kuah", 
    "Apem Kuk", 
    "Apem Putih", 
    "Apem Tepung Beras", 
    "Arsik", 
    "Asam Sunti", 
    "Asam pedas", 
    "Asam rujak", 
    "Asinan Bogor", 
    "Asinan Jakarta", 
    "Asinan Sukasari", 
    "Aunu", 
    "Aunu Senebre", 
    "Awok", 
    "Ayam Areh", 
    "Ayam Bacem", 
    "Ayam Bakar", 
    "Ayam Betutu", 
    "Ayam Goreng khas Sukabumi", 
    "Ayam Iloni", 
    "Ayam Kalasan", 
    "Ayam Masak Habang", 
    "Ayam Masak Paniki", 
    "Ayam Rica-Rica", 
    "Ayam Taliwang", 
    "Ayam Tangkap", 
    "Ayam bekakak", 
    "Ayam isi di bulu", 
    "Ayam pop", 
    "Babi Guling", 
    "Babi Kecap", 
    "Babi Panggang Karo", 
    "Babi Putar", 
    "Babi tore", 
    "Bada Reuteuek", 
    "Bagane", 
    "Bagea", 
    "Baje'", 
    "Bajigur", 
    "Bakmi Babat Kremes", 
    "Bakmi Godog", 
    "Bakmi Jawa", 
    "Bakmi Ketoprak", 
    "Bakmi Nyemek", 
    "Bakmoy", 
    "Bakpia", 
    "Bakso Kocok", 
    "Bakso Malang", 
    "Bakwan Malang", 
    "Bala-bala", 
    "Balado bawal", 
    "Balapis", 
    "Ballo/ Tuak", 
    "Balungan Hayam", 
    "Bandeng asap", 
    "Bandeng presto", 
    "Banding Bakar Marunda", 
    "Bandot", 
    "Bandrek", 
    "Bangket Durian", 
    "Bannang bannang", 
    "Banyumas", 
    "Baro'bo", 
    "Barongko", 
    "Baruasa", 
    "Baso sapi tengkleng", 
    "Bassang", 
    "Bata Anget", 
    "Batagor", 
    "Be Kokak Mekuah", 
    "Be Pasih Mesambel Matah", 
    "Bebek Balap", 
    "Bebek Betutu", 
    "Bebek Goreng", 
    "Bebek Kremes", 
    "Bebek Suwar-Suwir", 
    "Beer Djawa", 
    "Begana", 
    "Belut goreng", 
    "Beppa Janda", 
    "Beras Kencur", 
    "Beras rendang", 
    "Berengkes", 
    "Biapong", 
    "Biawan Baubar", 
    "Bie Pang", 
    "Bihun Goreng", 
    "Biji biji Jenever", 
    "Biji-biji", 
    "Bika", 
    "Bika Ambon", 
    "Bika Siana", 
    "Bikang", 
    "Bilis Gulung", 
    "Bingka Barandam", 
    "Bingka Dolu Gula Merah", 
    "Binte Biluhuta", 
    "Binyolos", 
    "Bipang", 
    "Bir Kocok", 
    "Bir Pletok", 
    "Blendung", 
    "Blora", 
    "Bluder/brudel", 
    "Bobengka", 
    "Bogor", 
    "Boh Puniaram", 
    "Bolu 8 Jam", 
    "Bolu Berendam", 
    "Bolu Gulung", 
    "Bolu Kambu", 
    "Bolu Kemojo/Kamboja", 
    "Bolu Kojo", 
    "Bolu Lapis", 
    "Bolu Peca", 
    "Bolu Rahayu", 
    "Bolu Toraja/Indo' Bade'", 
    "Bolu rampah", 
    "Bongko", 
    "Bothok", 
    "Botok Telur Asin", 
    "Brem", 
    "Brengkes", 
    "Brengkes Tempoyak", 
    "Brengkes Udang", 
    "Brongkos", 
    "Brownies Kukus", 
    "Buak Balak", 
    "Buak Lambang Sari", 
    "Bubuh Sagu", 
    "Bubuh Sumsum", 
    "Bubuh Tuak", 
    "Bubur Ayam Betawi", 
    "Bubur Bunting", 
    "Bubur Gunting", 
    "Bubur Habang Bubur Putih", 
    "Bubur Kacang Ijo", 
    "Bubur Kampiun", 
    "Bubur Pedas", 
    "Bubur Sagu", 
    "Bubur ayam Bunut", 
    "Bubur pulut hitam", 
    "Bubur tepung ubi kayu", 
    "Bulung Gadung", 
    "Bungkuk", 
    "Bunthil", 
    "Buras", 
    "Burgo", 
    "Busro", 
    "Ca Kwe", 
    "Cabuk Rambak", 
    "Cah Kangkung Belacan", 
    "Cakalang Bakar Rica", 
    "Cakalang Fufu", 
    "Cakalang Rica-Rica", 
    "Cake Buah Naga", 
    "Camme Ba'te", 
    "Camme Bendoro'", 
    "Camme Burak", 
    "Camme Tu'tuk", 
    "Cangkarok Karing", 
    "Cap Tikus", 
    "Capsay Petai", 
    "Carang Gesing", 
    "Carang Madu", 
    "Celimpungan", 
    "Cemplon", 
    "Cenil", 
    "Cimpa", 
    "Cimplung", 
    "Cindua", 
    "Cipera", 
    "Cireng", 
    "Ciwel", 
    "Cokelat Suzanna", 
    "Cokelat rendang", 
    "Colenak", 
    "Colo-colo", 
    "Combro", 
    "Coto Makassar", 
    "Cucur", 
    "Cucur Bujang", 
    "Cucuru Bayao", 
    "Cuwer", 
    "Cwie Mie Malang", 
    "Dabu dabu Lilang", 
    "Dadar", 
    "Dadiah", 
    "Dadoro'", 
    "Dakak-dakak", 
    "Dalca", 
    "Dalini Horbo", 
    "Dange", 
    "Dangi", 
    "Dangke", 
    "Daun ubi sambal belacan", 
    "Dawet", 
    "Dawet Ayu", 
    "Dawet Beras & Aci", 
    "Dawet Ireng", 
    "Demak", 
    "Dendeng Age", 
    "Dendeng balado", 
    "Dendeng batokok", 
    "Deppa Kau Kau/sawalla", 
    "Deppa Tori/Deppa Te'tekan", 
    "Docang", 
    "Doclang", 
    "Dodol Danau Salak", 
    "Dodol Garut", 
    "Dodol Hideung Ketan", 
    "Dodol Kacang-durian", 
    "Dodol Kandangan", 
    "Dodol Kenari", 
    "Dodol Legit", 
    "Dodol Pulut Hitam", 
    "Doidoi", 
    "Doko doko Cangkuling/ cangkuning", 
    "Dorokdok", 
    "Dudul", 
    "Dulinat", 
    "Dumbeg", 
    "Empal Asem", 
    "Empal Gentong", 
    "Empek-empek Adaan", 
    "Empek-empek Kapal Selam", 
    "Empek-empek Kerupuk", 
    "Empek-empek Kulit", 
    "Empek-empek Lenggang", 
    "Empek-empek Lenjer", 
    "Empek-empek Panggang", 
    "Empek-empek Pistel", 
    "Empek-empek Tahu", 
    "Empek-empek/pempek", 
    "Emping", 
    "Engkak Ketan", 
    "Enting-enting", 
    "Epok-epok", 
    "Es Apollo", 
    "Es Campur", 
    "Es Cendol", 
    "Es Dawet", 
    "Es Doger", 
    "Es Duren", 
    "Es Gempol", 
    "Es Goyobod", 
    "Es Kacang Merah", 
    "Es Kacang merah", 
    "Es Karet", 
    "Es Kopyor", 
    "Es Laksamana Mengamuk", 
    "Es Legen", 
    "Es Mocca", 
    "Es Puter", 
    "Es Sagwan", 
    "Es Teler", 
    "Es campur", 
    "Es sari rumput laut", 
    "Es tebak", 
    "Eungkot Paya", 
    "Eurimoo", 
    "Gado Gado", 
    "Gado-Gado", 
    "Gado-gado", 
    "Gagampam", 
    "Gagatas", 
    "Gagati", 
    "Gaguduh", 
    "Gajebo", 
    "Galamai", 
    "Gandus", 
    "Ganepuk Telur", 
    "Gangan Asam", 
    "Gangan Asam Daging", 
    "Gangan Asam Patin", 
    "Gangan Gadang Pisang", 
    "Gangan Humbut", 
    "Gangan Kaladi", 
    "Gangan Kangkung", 
    "Gangan Karuh", 
    "Gangan Ludeh Nangka", 
    "Gangan Luncar", 
    "Gangan Masak Karing", 
    "Gangan Nangka", 
    "Gangan Pisang", 
    "Gangan Rabung", 
    "Gangan Udang satang", 
    "Gangan Waluh", 
    "Gangang Batang Pisang", 
    "Gangang Nangka", 
    "Gangang Rabung", 
    "Gangang supan supan", 
    "Gangang tongkol", 
    "Gangsa", 
    "Ganngan Haliling", 
    "Gaplek", 
    "Garang Asem", 
    "Garigit", 
    "Garih", 
    "Garih Batanak", 
    "Gathot", 
    "Geblek", 
    "Gegeplak", 
    "Gehu", 
    "Gelamai Perentak", 
    "Gelemok", 
    "Gemblong", 
    "Gempol Plered", 
    "Gendar Ketan Hitam", 
    "Geplak", 
    "Gepuk", 
    "Gerang Tempe", 
    "Gethuk Pisang", 
    "Gethuk Runting", 
    "Gethuk goreng", 
    "Getuk", 
    "Gipang", 
    "Glotak", 
    "Gobak sagu", 
    "Godok-godok", 
    "Gogose", 
    "Gohu", 
    "Golla golla ganepo", 
    "Golla tare", 
    "Grangasem", 
    "Growol", 
    "Gubal", 
    "Gudangan", 
    "Gudeg", 
    "Gudeg Koyor", 
    "Gudeg Manggar", 
    "Gudeg Nangka", 
    "Gula Aren Cikeris", 
    "Gula Cakar", 
    "Gula Semut", 
    "Gulai", 
    "Gulai Balak", 
    "Gulai Malbi", 
    "Gulai Pakis", 
    "Gulai Siput", 
    "Gulai Taboh", 
    "Gulai Tempoyak", 
    "Gulai banak", 
    "Gulai cubadak", 
    "Gulai itiak", 
    "Gulai kambiang", 
    "Gulai kemumu", 
    "Gulai paku", 
    "Gulai pucuak ubi", 
    "Gulai tambusu", 
    "Gulai toco", 
    "Gule Goreng", 
    "Gule Rampoe", 
    "Gule-gule", 
    "Gulei Hiu", 
    "Gumpal", 
    "Gurame Bakar", 
    "HIntalu Karuang", 
    "Halua Kenari", 
    "Hampap/Haruan Kering Batanak", 
    "Haruan/tauman baubar", 
    "Heb'atu", 
    "Hekeng", 
    "Hintalu Jaruk", 
    "Hintalu Masak Habang", 
    "Horok-Horok", 
    "Hucap", 
    "Hundang Papai", 
    "Ikan Asam Pedas", 
    "Ikan Bakar Manokwari", 
    "Ikan Bakar Rica", 
    "Ikan Bakar dengan Colo-Colo", 
    "Ikan Bungkus", 
    "Ikan Holat", 
    "Ikan Kuah", 
    "Ikan Kuah Kuning", 
    "Ikan Monyet", 
    "Ikan Pais", 
    "Ikan Pakasam", 
    "Ikan Peda", 
    "Ikan Pekasam", 
    "Ikan Peletuk Masak Kuning", 
    "Ikan Rusip", 
    "Ikan Salai", 
    "Ikan Sale", 
    "Ikan Tikus", 
    "Ikan Ular Patola", 
    "Ikan baka", 
    "Ikan balado", 
    "Ikan rica", 
    "Intip Goreng", 
    "Ipau", 
    "Ja'pe Ayam", 
    "Jadah", 
    "Jadah Bacem", 
    "Jadah Blondo", 
    "Jadah Manten", 
    "Jadah Tempe", 
    "Jagung Bakar", 
    "Jagung Pipilan Bajarang", 
    "Jagung bose", 
    "Jaja Batun Duren", 
    "Jaja Begina", 
    "Jaja Bendu", 
    "Jaja Bikang", 
    "Jaja Engol", 
    "Jaja Godoh", 
    "Jaja Jongkok", 
    "Jaja Ketimus", 
    "Jaja Klepon", 
    "Jaja Lak-Lak", 
    "Jaja Sumping", 
    "Jaja Tain Buati", 
    "Jaja Uli misi Tape", 
    "Jaja Wajik", 
    "Jalang Kote", 
    "Jamu Beras Kencur", 
    "Jamu Kunir Asem", 
    "Jangan Kelor", 
    "Jangan Pakis", 
    "Jaruk Kalangkala", 
    "Jaruk Lumbu Kaladi Bapais", 
    "Jaruk Tarap", 
    "Jawa Tengah", 
    "Jejeruk", 
    "Jemblem", 
    "Jenang Apel", 
    "Jenang Candi", 
    "Jenang Gronthol", 
    "Jenang Jaket", 
    "Jenang Rumput laut", 
    "Jenang Sungsum", 
    "Jenang Waluh", 
    "Jepara", 
    "Jerangking", 
    "Jipang", 
    "Jojorong", 
    "Jongkong Ijo", 
    "Juadah Ketan", 
    "Juice Jagung Manis", 
    "Juice Tiga Rasa", 
    "Jukut Ares", 
    "Jukut Srombotan", 
    "Jukut Urab", 
    "Jus jagung", 
    "Juwawut", 
    "Kabuto", 
    "Kacang Atom", 
    "Kacang Bogares", 
    "Kacang Jepara", 
    "Kacang Kawangkoan", 
    "Kacang Oven", 
    "Kacang Pres", 
    "Kacang Rahayu", 
    "Kacang Sinjai", 
    "Kacang goyang", 
    "Kadonteng", 
    "Kajompi'", 
    "Kaladde", 
    "Kalakai Batumis", 
    "Kalalapon", 
    "Kalio", 
    "Kambalu", 
    "Kambang Tigaron Bajaruk", 
    "Kanji Rumbi", 
    "Kaoya Dudul", 
    "Kapurung", 
    "Karah", 
    "Karak", 
    "Karak kaliang", 
    "Karawang", 
    "Karedok", 
    "Karih Daging", 
    "Karupuk Rasa Bawang", 
    "Kasbi", 
    "Katemak", 
    "Katri mandi", 
    "Katri sala", 
    "Katupat Kandangan", 
    "Kawah", 
    "Kawis Cao", 
    "Kayapun/Bingka", 
    "Keceprek Melinjo", 
    "Keciput", 
    "Kek Pisang Villa", 
    "Kelicuk", 
    "Kemplang", 
    "Kemplang Goreng", 
    "Kemplang Panggang", 
    "Kepurun", 
    "Kerak Telor", 
    "Keripik Buah Naga", 
    "Keripik Kentang", 
    "Keripik Pisang", 
    "Keripik Sagu Bakar", 
    "Keripik Sagu Lenggang", 
    "Keripik Singkong", 
    "Keripik Tempe", 
    "Keripik Usus Ayam", 
    "Keripik sanjai", 
    "Kernas", 
    "Kerupuk", 
    "Kerupuk Antor", 
    "Kerupuk Atom", 
    "Kerupuk Bakar", 
    "Kerupuk Basah", 
    "Kerupuk Buah Naga", 
    "Kerupuk Cincin", 
    "Kerupuk Gonggong", 
    "Kerupuk Kerapu", 
    "Kerupuk Mi", 
    "Kerupuk Mlarat", 
    "Kerupuk Otak-Otak", 
    "Kerupuk Puli", 
    "Kerupuk Rambak", 
    "Kerupuk jangek", 
    "Kerupuk jariang", 
    "Kerupuk udang", 
    "Kerye", 
    "Ketan durian", 
    "Ketan sarikaya", 
    "Ketoprak", 
    "Keumamah", 
    "Kidu-Kidu", 
    "Kikicak", 
    "Kimlo", 
    "Kipang", 
    "Kipo", 
    "Klappertaart", 
    "Klepon", 
    "Kluntup", 
    "Kohu-Kohu dengan Kasbi Rebus", 
    "Kokoleh", 
    "Kolomben", 
    "Kolontong", 
    "Komoh", 
    "Kopi Hawaii", 
    "Kopi Kapal Tanker", 
    "Kota Karanganyar Kebumen", 
    "Koyabu", 
    "Koyong Lemuru", 
    "Kraca Cenil", 
    "Kripik Laron", 
    "Kroket", 
    "Kucur", 
    "Kudus", 
    "Kue 8 Jam", 
    "Kue Ali", 
    "Kue Bakiak", 
    "Kue Bangket", 
    "Kue Bangket Durian", 
    "Kue Bangket Jeruk Nipis", 
    "Kue Bangkit", 
    "Kue Batang Buruk", 
    "Kue Bawang", 
    "Kue Bingka Berendam", 
    "Kue Bingka Kentang", 
    "Kue Buah Melaka", 
    "Kue Cubit", 
    "Kue Dram Dram", 
    "Kue Dua Sebilik", 
    "Kue Jahe", 
    "Kue Lam", 
    "Kue Lapan Jam", 
    "Kue Maksuba", 
    "Kue Mangkuk Gula Merah", 
    "Kue Pepe", 
    "Kue Pulut Berinti", 
    "Kue Putu", 
    "Kue Rangi", 
    "Kue Satu", 
    "Kue Semprit", 
    "Kue Sus", 
    "Kue Tepung Kusoi", 
    "Kue apem betawi", 
    "Kue cucur", 
    "Kue jongkong", 
    "Kue unti", 
    "Kukis Kelapa", 
    "Kukuleh", 
    "Kulit Ayam Goreng", 
    "Kumbu", 
    "Kupang Lontong", 
    "Kupat Glabed", 
    "Kupat Tahu", 
    "Kupat tahu", 
    "Kuwah Boh Eungkot", 
    "Kuwah Eungkot Rambeue", 
    "Kuwah Eungkot Yee", 
    "Kuwah Itek", 
    "Kuwah Manok", 
    "Kuwah Pliek U", 
    "Kuwah Sie Kameng", 
    "Kuwah Tuhe", 
    "Kwetiau", 
    "Kwetiauw Siram", 
    "Labu Palu", 
    "Ladu", 
    "Lakatan Ba Inti", 
    "Lakatan Bahintti", 
    "Laksa", 
    "Laksa Bogor", 
    "Laksa Goreng", 
    "Laksan", 
    "Lakse", 
    "Lakso", 
    "Lalampa", 
    "Lalampar", 
    "Lamang", 
    "Lamang tapai", 
    "Lambok", 
    "Lampam", 
    "Lampam Baubar", 
    "Lampu lampu", 
    "Lanting", 
    "Lanun", 
    "Lapa-Lapa", 
    "Lapat Lakatan", 
    "Lapis", 
    "Lapis Legit", 
    "Lappa'-lappa'", 
    "Lappet", 
    "Lappet Gadong", 
    "Lappet Pohul-pohul", 
    "Lawa", 
    "Lawar", 
    "Ledre", 
    "Legomoro", 
    "Lema", 
    "Lemang", 
    "Lemeng", 
    "Lemet", 
    "Lempeng", 
    "Lempeng Legendar", 
    "Lempeng Pisang", 
    "Lempeng Telo", 
    "Lemper", 
    "Lempog", 
    "Lempok", 
    "Lempok Duren", 
    "Lempok Durian", 
    "Lenggang", 
    "Lengko", 
    "Lentog", 
    "Lepat Pisang", 
    "Lepet", 
    "Lepet Jagung", 
    "Lidah Buaya", 
    "Lodeh kikil", 
    "Lomok-Lomok", 
    "Lompong Sagu", 
    "Lontong", 
    "Lontong Balap", 
    "Lontong Campur", 
    "Lontong Cecek", 
    "Lontong Kari", 
    "Lontong Kikil", 
    "Lontong Kupang", 
    "Lontong Sayur Khas Betawi", 
    "Lontong Tuyuhan", 
    "Lontong balap", 
    "Lontong pitalah", 
    "Lontong sayur", 
    "Lopis", 
    "Lotek", 
    "Luluta", 
    "Lumpia Semarang", 
    "Lumpia Trubus", 
    "Luncar Kaladi", 
    "Lupis", 
    "Magelang", 
    "Maghadip", 
    "Maksuba", 
    "Mandai", 
    "Mangga Gedung Gincu", 
    "Mangut", 
    "Mangut Lele", 
    "Manisan Cianjur", 
    "Manisan Dorong", 
    "Manisan Pala", 
    "Manisan pala", 
    "Marak", 
    "Martabak Aceh", 
    "Martabak Lebaksiu", 
    "Martabak Legi", 
    "Masak Habang", 
    "Masak Kicap", 
    "Masak Kuning", 
    "Masak Paniki", 
    "Masak Puteh", 
    "Masak Tuha", 
    "Masak asam", 
    "Masam Keu'eueng", 
    "Massa'pote", 
    "Mata Kebo", 
    "Mega Mendung", 
    "Mendut", 
    "Menjes", 
    "Meuseukat", 
    "Mi Celor", 
    "Mi Goreng", 
    "Mi Koclok", 
    "Mi Kocok", 
    "Mi Tektek", 
    "Mi Toprak", 
    "Midaal", 
    "Mie Aceh", 
    "Mie Celor", 
    "Mie Gomak", 
    "Mie Lendir", 
    "Mie Sagu", 
    "Mie Siam Kuning", 
    "Mie Tarempa", 
    "Mie Tite", 
    "Mie Titi'", 
    "Mino", 
    "Misro", 
    "Mochi", 
    "Model", 
    "Mutiara Bagan Siapi-api", 
    "Nagasari/Doko'-doko'unti", 
    "Nande Dalle", 
    "Nande Kandoa'", 
    "Nanidugu", 
    "Naniura", 
    "Nase' Serpang", 
    "Nasi Becek", 
    "Nasi Begana", 
    "Nasi Blawu", 
    "Nasi Boran", 
    "Nasi Boranan", 
    "Nasi Bubuh", 
    "Nasi Bukhari", 
    "Nasi Bungkus", 
    "Nasi Dagang", 
    "Nasi Gandul", 
    "Nasi Gemuk", 
    "Nasi Godog", 
    "Nasi Goreng Babat", 
    "Nasi Goreng Daon Mengkudu", 
    "Nasi Goreng Gila", 
    "Nasi Goreng Jambal Petai", 
    "Nasi Goreng Jawa", 
    "Nasi Goreng Kambing", 
    "Nasi Goreng Kampung", 
    "Nasi Goreng Kari Kambing", 
    "Nasi Goreng Kuning", 
    "Nasi Goreng Magelang", 
    "Nasi Goreng Putih", 
    "Nasi Grombyang", 
    "Nasi Gurih", 
    "Nasi Jaha", 
    "Nasi Jenggo", 
    "Nasi Kapau", 
    "Nasi Kebuli", 
    "Nasi Krawu", 
    "Nasi Kucing", 
    "Nasi Kuning", 
    "Nasi Langgi", 
    "Nasi Lapola", 
    "Nasi Lemak", 
    "Nasi Liwet", 
    "Nasi Mawut", 
    "Nasi Megono", 
    "Nasi Minyak", 
    "Nasi Ndoreng", 
    "Nasi Pecel", 
    "Nasi Pindang", 
    "Nasi Pundut", 
    "Nasi Samin", 
    "Nasi Sumsum", 
    "Nasi Tempong", 
    "Nasi Tepeng", 
    "Nasi Timbel", 
    "Nasi Timbel Ciganea", 
    "Nasi Tomat", 
    "Nasi Tumpang", 
    "Nasi Tutug Oncom", 
    "Nasi Uduk", 
    "Nasi Wiwit", 
    "Nasi gandul", 
    "Nasi megono", 
    "Nasi pindang", 
    "Nasu Cemba", 
    "Nasu To Salukanan", 
    "Ndog Gludug", 
    "Nogo Sari", 
    "Nom Aeng", 
    "Nomoeng", 
    "Nopya", 
    "Oeiloni", 
    "Olos", 
    "Ombus-Ombus", 
    "Onde onde tawaro", 
    "Onde onde ubi kayu", 
    "Onde-onde", 
    "Ongol-Ongol", 
    "Ongol-ongol", 
    "Opak", 
    "Opak Ketan", 
    "Opor Ayam", 
    "Opor Tarung", 
    "Opor Telur", 
    "Orem Orem", 
    "Orok - orok", 
    "Oseng-oseng", 
    "Otak otak", 
    "Otak otak bandeng", 
    "Otak-otak", 
    "Pacco'", 
    "Pacri nanas", 
    "Pada' Basanga", 
    "Padamaran", 
    "Pais Udang", 
    "Pakasam Sapat", 
    "Palai rinuak", 
    "Pallu Basa", 
    "Pallu Butung", 
    "Pallu Kacci", 
    "Pallu Kaloa", 
    "Pallu Mara", 
    "Pampis", 
    "Panada", 
    "Pangatan", 
    "Pangek masin", 
    "Panggang Geleng", 
    "Panggang Ikan Mas", 
    "Pangsit", 
    "Papeda", 
    "Papuyu Basanga", 
    "Papuyu Baubar", 
    "Papuyu Baubar/Papuyu Bakar", 
    "Pare", 
    "Paserrek", 
    "Patah", 
    "Pati", 
    "Payeh", 
    "PeSalak", 
    "Peca sura", 
    "Pecak Gurame", 
    "Pecel", 
    "Pecel Gendar", 
    "Pecel Ikan Laut Panggang", 
    "Pecel Madiun", 
    "Pecel Phitik", 
    "Pecel Surabaya", 
    "Peco' Tammate", 
    "Pedda", 
    "Pekalongan", 
    "Pekating", 
    "Pelas", 
    "Pelasan", 
    "Pelasan Nus", 
    "Pempek Adaan", 
    "Pempek Isi Udang", 
    "Pempek Kapal Selam", 
    "Pempek Keriting", 
    "Pempek Kulit", 
    "Pempek Lenggang", 
    "Pempek Lenjer", 
    "Pempek Panggang", 
    "Pempek Pistel", 
    "Pempek Telor", 
    "Pendap", 
    "Pensi", 
    "Penyon", 
    "Pepes", 
    "Pepes Ikan Mas", 
    "Pepes Ikan mas", 
    "Pepes Jamur", 
    "Pergedel jagung", 
    "Perkedel Bondon", 
    "Perkedel Nike", 
    "Perut Ayam", 
    "Pesmo Gurami", 
    "Petis", 
    "Petis Bumbon", 
    "Petis Enthog", 
    "Petis Kangkung", 
    "Petis Tangkar", 
    "Peukasam Drien", 
    "Peunajoh Tho", 
    "Peuyeum", 
    "Peuyeum Bendul", 
    "Peyek Bayem", 
    "Peyek Dele", 
    "Peyek Jingking", 
    "Peyek Kacang", 
    "Pi'ja", 
    "Pilus", 
    "Pinaraci", 
    "Pindang Ayam", 
    "Pindang Daging/Tulang", 
    "Pindang Ikan patin", 
    "Pindang Jamur", 
    "Pindang Koyong", 
    "Pindang Salai", 
    "Pindang Serani", 
    "Pindang Tempe", 
    "Pindang Tetel", 
    "Pindang maranjat", 
    "Pindang pegagan", 
    "Pinyaram", 
    "Piong/Lemang Toraja", 
    "Pisang Epe", 
    "Pisang Goreng Pontianak", 
    "Pisang Ijo", 
    "Pisang Molen", 
    "Pisang Rampai", 
    "Plecing Ayam", 
    "Plecing Kangkung", 
    "Podak", 
    "Pok pia", 
    "Pokak Syarifah", 
    "Popaco", 
    "Pottre Nyellem", 
    "Puding Sagu", 
    "Pukis", 
    "Pukis Kelapa", 
    "Pulut", 
    "Pupudak", 
    "Puracit", 
    "Purwakarta", 
    "Puthu Lanang", 
    "Putre Nyelem", 
    "Putri Selat", 
    "Putu Cangkiri", 
    "Putu Mayang", 
    "Putu mayang", 
    "Putu piring", 
    "RW", 
    "Rabeg", 
    "Ragei/ Sate ba'", 
    "Ragi Pelasan", 
    "Rakik maco", 
    "Rangai", 
    "Rangginang Ketan", 
    "Rangkasusun", 
    "Rawon", 
    "Rembang", 
    "Rempe", 
    "Rempih Danggur", 
    "Rendang", 
    "Rengginang", 
    "Resep Kroket Kentang", 
    "Resep Soto Bandung", 
    "Rica Rica", 
    "Risoles", 
    "Roa", 
    "Ronde", 
    "Roti Buaya", 
    "Roti Jok", 
    "Roti Kecik", 
    "Roti Ketawa", 
    "Roti Kosong", 
    "Roti Mandarin", 
    "Roti Semir", 
    "Roti Unyil", 
    "Roti canai", 
    "Roti jala", 
    "Roti kirai", 
    "Roti pawa", 
    "Roti prata", 
    "Rujak Bebeg", 
    "Rujak Bulung", 
    "Rujak Cemplong", 
    "Rujak Cingur", 
    "Rujak Degan", 
    "Rujak Gobet", 
    "Rujak Kecut", 
    "Rujak Kuah Pindang", 
    "Rujak Legi", 
    "Rujak Lethok", 
    "Rujak Lontong", 
    "Rujak Manis", 
    "Rujak Mie", 
    "Rujak Petis", 
    "Rujak Sayur", 
    "Rujak Soto", 
    "Rujak Tibah", 
    "Rujak Uleg", 
    "Rujak Uni", 
    "Rujak maharaja", 
    "Ruti Cane", 
    "Ruti Jala", 
    "STMJ", 
    "Sa'ut", 
    "Sagon Bakar", 
    "Sagon Kota Gede", 
    "Sagon bakar", 
    "Sagu Lemak", 
    "Sagu lenggang", 
    "Saguer", 
    "Sakko sakko", 
    "Sakoteng", 
    "Saksang", 
    "Salak Bali", 
    "Salatiga", 
    "Saluang Basanga", 
    "Sambai Asam Udeueng", 
    "Sambai On Peugaga", 
    "Sambal Belacan", 
    "Sambal Blacan", 
    "Sambal Goreng Campur", 
    "Sambal Goreng Krecek Kacang Tolo", 
    "Sambal Goreng Pakasam", 
    "Sambal Kemang", 
    "Sambal Kweni", 
    "Sambal Lingkung", 
    "Sambal Mbacang", 
    "Sambal Pepaya", 
    "Sambal Popat Asam Pelam", 
    "Sambal Rias", 
    "Sambal Tuk Tuk", 
    "Sambal belacan", 
    "Sambal bilis kacang", 
    "Sambal jokjok", 
    "Sambal lingkong gonggong", 
    "Sambal mangga", 
    "Sambala' Bandiki'", 
    "Sambalado tanak", 
    "Sambam Lauk", 
    "Sambel Goreng Krecek", 
    "Sambel Hebi", 
    "Sambel Ijo", 
    "Sambel Oncom", 
    "Sambel Tumpang", 
    "Samu ikan-tarap-tiwadak", 
    "Sangsang", 
    "Sapat Siam Baubar", 
    "Sara'bba", 
    "Sarabi", 
    "Sarang balam", 
    "Sari Kacang Hijau", 
    "Sari Pangantin", 
    "Sarikaya", 
    "Sarimuka", 
    "Sarondeng", 
    "Sate", 
    "Sate Ambal", 
    "Sate Ayam Blora", 
    "Sate Ayam Ponorogo", 
    "Sate Bandeng", 
    "Sate Banjar", 
    "Sate Bebek", 
    "Sate Bulayak", 
    "Sate Buntel", 
    "Sate Itik Brebes", 
    "Sate Kablet", 
    "Sate Kakul", 
    "Sate Kelinci", 
    "Sate Kerang", 
    "Sate Kikil", 
    "Sate Klathak", 
    "Sate Kocor", 
    "Sate Kolombi", 
    "Sate Lilit", 
    "Sate Manis", 
    "Sate Maranggi", 
    "Sate Matang", 
    "Sate Padang", 
    "Sate Pariaman", 
    "Sate Pentul", 
    "Sate Penyu", 
    "Sate Sapi", 
    "Sate Sapi Plarangan", 
    "Sate Sapi Ungaran", 
    "Sate Sarepeh", 
    "Sate Suruh", 
    "Sate Tegal", 
    "Sate Tusuk", 
    "Sate Winong", 
    "Sate kerang", 
    "Sate pokea", 
    "Sate, Keripik Bekicot", 
    "Sawot", 
    "Sayor Ganemo", 
    "Sayor Leilem", 
    "Sayor Pangi", 
    "Sayor bunga popaya", 
    "Sayor daong popaya", 
    "Sayor pakis", 
    "Sayur Asam", 
    "Sayur Asam Kacang Merah", 
    "Sayur Bebanci", 
    "Sayur Besan", 
    "Sayur Gabus Pucungcak", 
    "Sayur Ganemu", 
    "Sayur Kasam", 
    "Sayur Kelor", 
    "Sayur Kesrut", 
    "Sayur Labu Siam", 
    "Sayur Merica", 
    "Se'i", 
    "Seblak", 
    "Sega Jamblang", 
    "Sega Lengko", 
    "Sego Abang", 
    "Sego Ayam", 
    "Sego Gobyos", 
    "Sego Goreng Babat Semarang", 
    "Sego Kucing", 
    "Sego Kuning", 
    "Sego Tempong", 
    "Sekubal/Ketan Lapis", 
    "Selat", 
    "Selat Solo", 
    "Sele Nenas", 
    "Semanggi", 
    "Semar Mendem", 
    "Semar Mesem", 
    "Semarang", 
    "Semprong", 
    "Semur", 
    "Semur Betawi", 
    "Semur Jengkol", 
    "Semur Terung Betawi", 
    "Serabi", 
    "Serabi Bogor", 
    "Serabi Notosuman", 
    "Serabi Oncom", 
    "Serbat", 
    "Serondeng", 
    "Seruwit", 
    "Sie Reuboh", 
    "Simping", 
    "Sinonggi", 
    "Siput Gonggong", 
    "Siput sedot", 
    "Sirup Kawis", 
    "Slada Gumbili", 
    "So'ri", 
    "Soami", 
    "Solo", 
    "Songkolo/Sokko'", 
    "Sop Kaki Kambing", 
    "Sop Kikil", 
    "Sop Konro", 
    "Sop Saudara", 
    "Sop Sumsum", 
    "Sop Ubi", 
    "Sop Udang", 
    "Sop ikan Batam", 
    "Sosis Solo", 
    "Soto Ayam", 
    "Soto Ayam Tasik", 
    "Soto Bandung", 
    "Soto Banjar", 
    "Soto Betawi", 
    "Soto Cirebon", 
    "Soto Daging Sapi", 
    "Soto Gading", 
    "Soto Jepara", 
    "Soto Jogomertan", 
    "Soto Kediri", 
    "Soto Kudus", 
    "Soto Kuning", 
    "Soto Lamongan", 
    "Soto Medan", 
    "Soto Mi", 
    "Soto Padang", 
    "Soto Pekalongan", 
    "Soto Petanahan", 
    "Soto Sadang", 
    "Soto Semarang", 
    "Soto Tangkar", 
    "Soto Tauco", 
    "Soto Tegal", 
    "Soto kemiri", 
    "Sotong masak hitam", 
    "Srabi Kocor", 
    "Srabi Solo", 
    "Sragen", 
    "Srikayo", 
    "Srombotan", 
    "Sroto Sokaraja", 
    "Stick Tahu", 
    "Sukabumi", 
    "Sumpiuh", 
    "Sup Brenebon", 
    "Susen", 
    "Susuru", 
    "Sutra Ambon", 
    "Suwar-suwir", 
    "Swiekee Kuah", 
    "Tahu Acar", 
    "Tahu Aci", 
    "Tahu Bulat", 
    "Tahu Gejrot", 
    "Tahu Gimbal", 
    "Tahu Kuning", 
    "Tahu Kupat", 
    "Tahu Lontong", 
    "Tahu Pletok", 
    "Tahu Pong", 
    "Tahu Sumedang", 
    "Tahu Tek", 
    "Tahu Telur", 
    "Tahu Wa", 
    "Tahu campur", 
    "Tahu petis", 
    "Tajin Shobih", 
    "Talam Udang", 
    "Tanggo-tanggo", 
    "Taoge Goreng", 
    "Taoto", 
    "Tape", 
    "Tape Ketan", 
    "Tar Piring", 
    "Taripang", 
    "Tarung Babanam Basantan", 
    "Tauco Cianjur", 
    "Tauge Goreng", 
    "Tegal", 
    "Tegean", 
    "Teh Gopek", 
    "Teh Hijau", 
    "Teh Jahe Keningar", 
    "Teh Kawa", 
    "Teh Kocok", 
    "Teh Obeng", 
    "Teh Poci", 
    "Teh Prendjak", 
    "Teh Tarik", 
    "Teh talua", 
    "Tekwan", 
    "Tello Penyyu", 
    "Telubuk Sayur", 
    "Telur Asin Brebes", 
    "Telur pulut", 
    "Tempe Benguk", 
    "Tempe Gembos", 
    "Tempe Gembus", 
    "Tempe Goreng", 
    "Tempe Koro", 
    "Tempe Penyet", 
    "Tempe Tahu Bacem", 
    "Tempe mendoan", 
    "Tempoyak", 
    "Tengkleng", 
    "Tepo", 
    "Terasi Petis Bonang", 
    "Terites", 
    "Terung Tumis", 
    "Thiwul", 
    "Tili Aya", 
    "Timbungan", 
    "Timlo", 
    "Timphan", 
    "Timus", 
    "Tinorangsak", 
    "Tinutuan", 
    "Tipa-tipa", 
    "Toge Goreng Jasinga Bogor", 
    "Toge Tauco", 
    "Tok-tok", 
    "Tollo' Burak", 
    "Tollo' Pa'karing", 
    "Tollo' Pammarasan", 
    "Tollo' Semba", 
    "Tollo' Utan Bulunangko", 
    "Tollo' Utan Pangi", 
    "Tolu-tolu", 
    "Tongseng", 
    "Topi Baja", 
    "Trancam", 
    "Trasikan", 
    "Tuak", 
    "Tuak Badeg", 
    "Tum", 
    "Tumbang Goreng", 
    "Tumpeng", 
    "Tuturuga", 
    "Ubi Bakar", 
    "Uceng uceng", 
    "Ulang-ulang", 
    "Ulin-ulin", 
    "Ungrung", 
    "Untuk", 
    "Upak", 
    "Urap", 
    "Urap - Urap", 
    "Urutan Tabanan", 
    "Using-using Hundang Papai", 
    "Using-using Kangkung", 
    "Using-using Tarung", 
    "Usus Goreng", 
    "Uyen", 
    "Wadai", 
    "Wadai Bapulas", 
    "Wadai Gayam", 
    "Wadai Pare", 
    "Wadi", 
    "Wajeb", 
    "Wajik", 
    "Wajik Ketan", 
    "Walang Goreng", 
    "Weci", 
    "Wedang Dongo", 
    "Wedang Gaul", 
    "Wedang Jahe", 
    "Wedang Pekak", 
    "Wedang Ronde", 
    "Wedang Secang", 
    "Wedang Sekojo", 
    "Wedang Uwuh", 
    "Woku belanga", 
    "Yangko", 
    "Yogyakarta", 
    "[[Masak Putih]", 
    "cecek", 
    "cetot", 
    "iwak peyek", 
    "jenang kudus", 
    "kopi Jos arang", 
    "paisan", 
    "pepes asam belimbing", 
    "pepes tempoyak", 
    "sapat siam baubar", 
    "sate semen", 
    "tiwul"
])